# Generated by Django 3.0 on 2019-08-09 18:27

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domainname', models.CharField(default='DEFAULT', max_length=30)),
                ('fullurlname', models.CharField(default='DEFAULT', max_length=65)),
                ('upload_file', models.FileField(upload_to=django.core.files.storage.FileSystemStorage(location='upload/file'))),
                ('Image', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='media/photos'), upload_to='')),
                ('UploadPDF', models.FileField(upload_to=django.core.files.storage.FileSystemStorage(location='upload/pdf'))),
            ],
        ),
        migrations.CreateModel(
            name='DomainChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domainchannelname', models.CharField(default='DEFAULT', max_length=30)),
                ('fullurlname', models.CharField(default='DEFAULT', max_length=65)),
                ('upload_file', models.FileField(upload_to=django.core.files.storage.FileSystemStorage(location='upload/file'))),
                ('Image', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='media/photos'), upload_to='')),
                ('UploadPDF', models.FileField(upload_to=django.core.files.storage.FileSystemStorage(location='upload/pdf'))),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domainchannels', to='app.Domain')),
            ],
        ),
        migrations.CreateModel(
            name='UploadImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100)),
                ('upload_file', models.FileField(upload_to=django.core.files.storage.FileSystemStorage(location='upload/file'))),
                ('Image', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='media/photos'), upload_to='')),
                ('UploadPDF', models.FileField(upload_to=django.core.files.storage.FileSystemStorage(location='upload/pdf'))),
            ],
        ),
        migrations.CreateModel(
            name='UploadPDF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100)),
                ('pdf', models.FileField(upload_to=django.core.files.storage.FileSystemStorage(location='upload/pdf'))),
            ],
        ),
        migrations.CreateModel(
            name='UserSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_file', models.FileField(upload_to=django.core.files.storage.FileSystemStorage(location='upload/file'))),
                ('Image', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='media/photos'), upload_to='')),
                ('UploadPDF', models.FileField(upload_to=django.core.files.storage.FileSystemStorage(location='upload/pdf'))),
                ('theme1', models.CharField(choices=[('DEFAULT', 'Default'), ('green', 'Forest'), ('orange', 'Fruity'), ('springgreen', 'Limey'), ('blue', 'Cold'), ('red', 'Hot'), ('yellow', 'Sunny'), ('spaceinvaders', 'Space Invaders Game'), ('pacman', 'PacMan Game'), ('chess', 'MultiUser Chess Game'), ('adventure', 'MultiUser Adventure Game'), ('TI', 'TI Games')], default='DEFAULT', max_length=30)),
                ('layout1', models.CharField(choices=[('DEFAULT', 'Default'), ('VERTICAL', 'Vertical'), ('HORIZONTAL', 'Horizontal')], default='DEFAULT', max_length=30)),
                ('theme2', models.CharField(choices=[('DEFAULT', 'Default'), ('green', 'Forest'), ('orange', 'Fruity'), ('springgreen', 'Limey'), ('blue', 'Cold'), ('red', 'Hot'), ('yellow', 'Sunny'), ('spaceinvaders', 'Space Invaders Game'), ('pacman', 'PacMan Game'), ('chess', 'MultiUser Chess Game'), ('adventure', 'MultiUser Adventure Game'), ('TI', 'TI Games')], default='DEFAULT', max_length=30)),
                ('layout2', models.CharField(choices=[('DEFAULT', 'Default'), ('VERTICAL', 'Vertical'), ('HORIZONTAL', 'Horizontal')], default='DEFAULT', max_length=30)),
                ('usermonitor', models.CharField(choices=[('Y', 'Yes'), ('y', 'Yes'), ('N', 'No'), ('n', 'No')], default='N', max_length=2)),
                ('useradmin', models.CharField(choices=[('Y', 'Yes'), ('y', 'Yes'), ('N', 'No'), ('n', 'No')], default='N', max_length=2)),
                ('gameadmin', models.CharField(choices=[('Y', 'Yes'), ('y', 'Yes'), ('N', 'No'), ('n', 'No')], default='N', max_length=2)),
                ('domainrestriction', models.CharField(choices=[('Y', 'Yes'), ('y', 'Yes'), ('N', 'No'), ('n', 'No')], default='N', max_length=2)),
                ('domainchannelrestriction', models.CharField(choices=[('Y', 'Yes'), ('y', 'Yes'), ('N', 'No'), ('n', 'No')], default='N', max_length=2)),
                ('messagerestriction', models.CharField(choices=[('Y', 'Yes'), ('y', 'Yes'), ('N', 'No'), ('n', 'No')], default='N', max_length=2)),
                ('agerestriction', models.CharField(choices=[('Y', 'Yes'), ('y', 'Yes'), ('N', 'No'), ('n', 'No')], default='N', max_length=2)),
                ('flagged', models.CharField(choices=[('Y', 'Yes'), ('y', 'Yes'), ('N', 'No'), ('n', 'No')], default='N', max_length=2)),
                ('domainchannels', models.ManyToManyField(blank=True, related_name='manytomanydomainchannelusers', to='app.DomainChannel')),
                ('domains', models.ManyToManyField(related_name='manytomanydomainusers', to='app.Domain')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usersettings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_file', models.FileField(upload_to=django.core.files.storage.FileSystemStorage(location='upload/file'))),
                ('Image', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='media/photos'), upload_to='')),
                ('UploadPDF', models.FileField(upload_to=django.core.files.storage.FileSystemStorage(location='upload/pdf'))),
                ('code', models.CharField(choices=[('DEFAULT', 'Default Message'), ('GENERALMSG', 'General Message'), ('ATTACHMENTMSG', 'Attachments Message'), ('RESPONSEMSG', 'Response Message'), ('HAPPYFACEMSG', 'HAPPY FACE Message'), ('SADFACEMSG', 'SAD FACE Message'), ('IMOGIMSG', 'IMOGI Message'), ('HTMLMSG', 'HTML Message'), ('PDFMSG', 'PDF Message'), ('IMAGEMSG', 'IMAGE Message'), ('FLAGMSG', 'FLAG Message'), ('CREATEGAMEPACMAN', 'Create A PACMAN Game'), ('ASSIGNGAMEPACMAN', 'Assign User to a PACMAN Game'), ('STARTGAMEPACMAN', 'Start PACMAN Game'), ('RESTARTGAMEPACMAN', 'ReStart PACMAN Game'), ('STOPGAMEPACMAN', 'Stop PACMAN Game'), ('UPDATEGAMEPACMAN', 'Update PACMAN Game'), ('DELETEGAMEPACMAN', 'Delete PACMAN Game'), ('CREATEGAMECHESS', 'Create A CHESS Game'), ('ASSIGNGAMECHESS', 'Assign User to a CHESS Game'), ('STARTGAMECHESS', 'Start CHESS Game'), ('RESTARTGAMECHESS', 'ReStart CHESS Game'), ('STOPGAMECHESS', 'Stop CHESS Game'), ('UPDATEGAMECHESS', 'Update CHESS Game'), ('DELETEGAMECHESS', 'Delete CHESS Game'), ('CREATEGAMESPACEINVADERS', 'Create A TI99 SPACE INVADERS Game'), ('ASSIGNGAMESPACEINVADERS', 'Assign User to a TI99 SPACE INVADERS Game'), ('STARTGAMESPACEINVADERS', 'Start TI99 SPACE INVADERS Game'), ('RESTARTGAMESPACEINVADERS', 'ReStart TI99 SPACE INVADERS Game'), ('STOPGAMESPACEINVADERS', 'Stop TI99 SPACE INVADERS Game'), ('UPDATEGAMESPACEINVADERS', 'Update TI99 SPACE INVADERS Game'), ('DELETEGAMESPACEINVADERS', 'Delete TI99 SPACE INVADERS Game'), ('CREATETASK', 'Create A Task'), ('ASSIGNTASK', 'Assign User to a Task'), ('UPDATETASK', 'Update Task'), ('DELETETASK', 'Delete Task'), ('NEWPROJECT', 'Create A Project'), ('ASSIGNPROJECT', 'Assign A Project'), ('UPDATEPROJECT', 'Update A Project'), ('DELTEPROJECT', 'Delete A Project'), ('PRIVATEMSG', 'Private Message'), ('ALLINTHISDOMAINCHANNELMSG', 'All in this Domain Channel Message'), ('ALLINTHISDOMAINMSG', 'All in this Domain Message'), ('ALLDOMAINSMSG', 'All Domains Message')], default='DEFAULT', max_length=30)),
                ('note', models.CharField(default='no entry', max_length=200)),
                ('senttodomain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senttodomainmessages', to='app.Domain')),
                ('senttodomainchannel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senttodomainchannelmessages', to='app.DomainChannel')),
                ('senttouser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senttomessages', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usermessages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DomainChannelSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('DEFAULT', 'Default'), ('green', 'Forest'), ('orange', 'Fruity'), ('springgreen', 'Limey'), ('blue', 'Cold'), ('red', 'Hot'), ('yellow', 'Sunny'), ('spaceinvaders', 'Space Invaders Game'), ('pacman', 'PacMan Game'), ('chess', 'MultiUser Chess Game'), ('adventure', 'MultiUser Adventure Game'), ('TI', 'TI Games')], default='DEFAULT', max_length=30)),
                ('layout', models.CharField(choices=[('DEFAULT', 'Default'), ('VERTICAL', 'Vertical'), ('HORIZONTAL', 'Horizontal')], default='DEFAULT', max_length=30)),
                ('upload_file', models.FileField(upload_to=django.core.files.storage.FileSystemStorage(location='upload/file'))),
                ('Image', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='media/photos'), upload_to='')),
                ('UploadPDF', models.FileField(upload_to=django.core.files.storage.FileSystemStorage(location='upload/pdf'))),
                ('domainchannel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domainchannelsettings', to='app.DomainChannel')),
            ],
        ),
    ]
